[package]
name = "mediadcl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audiotags = "0.4.1"
fs-err = "2.9.0"
walkdir = "2.3.2"
